name: Browserstack

on:
  push:
    branches:
      - 3.x-stable
  # Once a week every Tuesday
  schedule:
    - cron: "12 2 * * 2"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 22.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ matrix.BROWSER }} - ${{ github.sha }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          - 'IE_10'
          - 'IE_9'
          - 'Safari_latest'
            # JTR doesn't take into account the jump from Safari 18 to 26,
            # so we need to specify versions explicitly.
            # See https://github.com/jquery/jquery-test-runner/issues/17
          - 'Safari_18'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Edge_18'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - 'Firefox_140'
          - 'Firefox_128'
          - 'Firefox_115'
          - 'Firefox_102'
          - 'Firefox_91'
          - 'Firefox_78'
          - 'Firefox_60'
          - 'Firefox_48'

          - '_:iPhone 17_iOS_26'
          - '_:iPhone 16_iOS_18'
          - '_:iPhone 15 Pro_iOS_17'
          - '_:iPhone 14_iOS_16'
          # None of the iOS 15 devices currently work; the browser
          # doesn't even start.
          # - '_:iPhone 13_iOS_15'
          - '_:iPhone 12_iOS_14'
          - '_:iPhone 11_iOS_13'
          # iOS 12 & older is not officially supported by BrowserStack as
          # it mostly runs on emulators instead of real devices. We include
          # those versions as long as they still work.
          - '_:iPhone XS_iOS_12'
          - '_:iPhone X_iOS_11'
          # There's no longer any iPhone device or emulator running iOS 8-10
          # available on BrowserStack. Skip testing on these versions.
          # - '_:iPhone 7_iOS_10'
          # - '_:iPhone 6S_iOS_9'
          # - '_:iPhone 6_iOS_8'
          # iOS 7 emulators no longer work properly
          # - '_:iPhone 5S_iOS_7'

          - '_:iPad Air 13 2025_iOS_26'
          - '_:iPad Air 13 2025_iOS_18'

          # iOS 10 is a tier 4 device as of January 2025 and its availability
          # is poor, leading to frequent test timeouts. Skip testing on it.
          # See https://www.browserstack.com/device-tiers
          # - '__iOS_10'

          # Versions below are not officially supported by BrowserStack as
          # they use emulators instead of real devices. We include them as
          # long as they still work.
          - '__iOS_9'
          - '__iOS_8'
          # iOS 7 emulators no longer work properly
          # - '__iOS_7'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Pretest script
        run: npm run pretest

      - name: Test
        run: |
          npm run test:unit -- -v -c jtr-ci.yml \
            --browserstack "${{ matrix.BROWSER }}" \
            --run-id ${{ github.run_id }} \
